# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 8
#
# Initialize kernel
/run/initialize
#
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
#
/process/inactivate hadElastic
# 
/gun/particle deuteron
/gun/energy 2 MeV
#
/run/printProgress 1000000
#
/run/beamOn 1000000
